template: Hello, %s!
defaultName: Stranger1

logging:
  level: INFO
  loggers:
      org.glassfish.jersey.filter.LoggingFilter: INFO
      # org.hibernate.SQL: DEBUG
      # org.hibernate.type: TRACE
  appenders:
    - type: file
      archive: true
      timeZone: IST
      logFormat: "[]%highlight(%-5level)[ekl-birost-hub] [%date] [%thread] [%cyan(%logger{0})]: %message%n"
      currentLogFilename: ./logs/pantrycar.log
      archivedLogFilenamePattern: ./logs/pantrycar-%d{yyyy-MM-dd-HH}.log
      archivedFileCount: 50
    - type: console
      timeZone: IST
      logFormat: "%highlight(%-5level)[pantrycar] [%date] [%yellow(%X{txnId})] [%thread] [%cyan(%logger{0})]: %message%n"


database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://pantry-car-dev.cp7t2sczmqdd.us-west-2.rds.amazonaws.com/pantry_car
  user: pantry
  password: adminadmin
  minSize: 8
  maxSize: 32
  properties:
     hibernate.connection.driver_class: com.mysql.jdbc.Driver
     hibernate.dialect : org.hibernate.dialect.MySQLDialect
     hibernate.hbm2ddl.auto: update
     hibernate.format_sql: true
     maxWaitForConnection: 1s
     validationQuery: "/* MyService Health Check */ SELECT 1"
     checkConnectionWhileIdle: true